export const START_CLASS = 'START_CLASS'
export const END_CLASS = 'END_CLASS'

export const START_P2P = 'START_P2P'
export const STOP_P2P = 'STOP_P2P'

export const SEND_MESSAGE = 'SEND_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'

/** p2p */
export const UPDATE_PEER_OBJECT = 'UPDATE_PEER_OBJECT'
export const UPDATE_LOCAL_STREAM = 'UPDATE_LOCAL_STREAM'
export const UPDATE_REMOTE_STREAM = 'UPDATE_REMOTE_STREAM'

/** user */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const UPDATE_ROOM_INFO = 'UPDATE_ROOM_INFO'

/** socket */
export const OPEN_WEBSOCKET = 'OPEN_WEBSOCKET'
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET'
export const CONNECT_SOCKET_ERROR = 'CONNECT_SOCKET_ERROR'
export const UPDATE_SOCKET_OBJECT = 'UPDATE_SOCKET_OBJECT'
